### ISSUE TITLE
Bug: Meta information not included in JSON download

### ISSUE THREAD

**Issue by JamesParrish** [AdmiralGT/botc-scripts#107]
When creating a script it is possible to add meta information (script name, author and logo) to the JSON. It appears that this information is not being included when the JSON is downloaded.

Example meta data: `[{"id": "_meta", "logo": "https://i.imgur.com/3NtsM1Q.png", "name": "Don't Miss", "author": "James P"},{"id":"empath"}...`

Replication
- Add meta data to a JSON file (testable by loading the JSON to https://clocktower.online/)
- Upload JSON
- Download JSON
- Meta data is not included in the downloaded JSON

**Comment by AdmiralGT** [comment]
As discussed, not a bug, you just forgot to upload with _meta

https://botc-scripts.azurewebsites.net/?search=&script_type=&include=_meta&exclude=&author=
