### ISSUE TITLE
Feature: Limit Similar Scripts by script type (Teensyville/Regular)

### ISSUE THREAD

**Issue by JamesParrish** [AdmiralGT/botc-scripts#170]
On the script page (eg https://botc-scripts.azurewebsites.net/script/60) there is a tab which shows similar scripts. When the user views similar scripts for a Teensyville script they are shown full-size regular scripts as well as Teensyville scripts. This can be useful for if someone wants to find a similar theme for a larger game, but not for finding similarly themed Teensyville scripts.

I suggest adding an option to allow the user to filter similar scripts to Teensyville, Regular or All Scripts

**Comment by AdmiralGT** [comment]
I've added separate lists for Full and Teensy scripts.
