### ISSUE TITLE
Bug: The previous two versions uploaded fine. Now I get an error message saying my script title doesn't match or my name doesn't match. They do match the original, so what is taking the spaces out? Brad Fortner doesn't match "BradFortner". Of course the spaces were there before.

### ISSUE THREAD

**Issue by Darby-Lols** [AdmiralGT/botc-scripts#219]
**Describe the bug**

**When did it happen**
Please try to be as accurate as possible, as this will help in correlating logs/metrics from the server.

**To Reproduce**
Is this problem reproduceable, if so, please provide the steps required to reproduce the behavior:

**Screenshots**

**Browser details:**
If this problem is related to the UI (User Interface), please provide as much information as possible about the browser version you are using.

**Additional context**
Add any other context about the problem here e.g. the JSON/PDF of the script

**Comment by AdmiralGT** [comment]
Any chance you could add the JSON as an attachment so I can take a look?

**Comment by AdmiralGT** [comment]
My guess though would be that you've added the metadata to the JSON and it's complaining of a mismatch.

Alternatively, try using the "Upload new version" button on the script you want to update. This will fill in the fields from the previous version and so you just need to update the version and attach a new PDF + JSON.

**Comment by Darby-Lols** [comment]
I've left the library (computers), but I'll try again later. Thanks.

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 30, 2022 at 1:42 PM, Geoff ***@***.***> wrote:   


My guess though would be that you've added the metadata to the JSON and it's complaining of a mismatch.

Alternatively, try using the "Upload new version" button on the script you want to update. This will fill in the fields from the previous version and so you just need to update the version and attach a new PDF + JSON.

**Comment by AdmiralGT** [comment]
Currently the script tool removes spaces from the Author and Name fields when creating a script in Chrome. This means if you try to upload a script and fill the form in with a space in the Name or Author field, it will fail validation.

This is a bug in the official script tool, but until that's resolved I've temporarily removed that validation against the JSON `_meta` fields and just used that provided in the form.

I'm tracking the full resolution to that in https://github.com/AdmiralGT/botc-scripts/issues/220 but if you try uploading now it should work.

**Comment by Darby-Lols** [comment]
OK. Thanks.

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 31, 2022 at 2:08 PM, Geoff ***@***.***> wrote:   


Currently the script tool removes spaces from the Author and Name fields when creating a script in Chrome. This means if you try to upload a script and fill the form in with a space in the Name or Author field, it will fail validation.

This is a bug in the official script tool, but until that's resolved I've temporarily removed that validation against the JSON _meta fields and just used that provided in the form.

I'm tracking the full resolution to that in #220 but if you try uploading now it should work.
