### ISSUE TITLE
Claim: A Day on the Docks

### ISSUE THREAD

**Issue by XDelta** [AdmiralGT/botc-scripts#301]
**Which script(s) would you like to claim?**
https://botcscripts.com/script/1642/1.1.0

**How would you like to be represented as the Author**
Delta

I uploaded a new version of my script https://botcscripts.com/script/1292/1.0.0 using the button on it's page but it appears that it wasn't assigned to me as the creator for some reason? #302

**Comment by AdmiralGT** [comment]
I've moved this to be a version of 1292 rather than a new script so ownership should now have returned correctly. I've responded in #302 for the actual bug.

@XDelta let me know if you'd like the name updated from "A day on the docks" to "A Day on the Docks" and I can update 1292 to reflect that.

**Comment by XDelta** [comment]
Much appreciated! Yeah, if you can update the casing on 1292.

**Comment by AdmiralGT** [comment]
Done
