### ISSUE TITLE
Bug: I am not able to upload any script anymore without a Server Error

### ISSUE THREAD

**Issue by mbungert** [AdmiralGT/botc-scripts#341]
Unfortunately, I am not able to upload any script anymore. I always get a 500 server error. Is it possible I crashed my account somehow? Is there anyway I can hand you over my user account without putting it directly in the ticket?

**Comment by AdmiralGT** [comment]
@mbungert Do you have a copy of the script you're trying to upload?

**Comment by AdmiralGT** [comment]
Turned out there's been a bug in uploading the new script format when uploading a new script. That's now been fixed in https://github.com/AdmiralGT/botc-scripts/pull/342
