### ISSUE TITLE
Bug: Characters dissappear from the json file in foreign languages

### ISSUE THREAD

**Issue by h3oCharles** [AdmiralGT/botc-scripts#345]
the script in question https://botc-scripts.azurewebsites.net/script/1998/2.0.0

when downloading a JSON file of a script in a foreign language (polish, in this case), it has some characters blank, making them not appear in the script when using external tools to generate scripts in foreign languages

it's worth mentioning that the Polish translation is a work in progress, and therefore inconsistent, as in, not everything is translated, so some things are kept in English. But notice how some characters appear in English, but some characters are just straight-up gone

is there any reliable way to ask for updates to translations? which database or spreadsheet are you using to fetch translations from?

**Screenshots**

![chrome_rRFuXzcxrq](https://github.com/AdmiralGT/botc-scripts/assets/8020330/8cc430f3-d122-458b-a3e5-e12b01518988)
preview of the generated script in scriptmaker.fly.dev - notice that 2 townsfolk, 1 minion, 2 demons, and 1 traveler are missing

![image](https://github.com/AdmiralGT/botc-scripts/assets/8020330/11128e05-5116-410d-bf75-5db820207d3f)
after formatting the JSON, I spotted some blank curly brackets between the empath and balloonist

![Most Popular-ish (Autumn 2023) v2 (1)](https://github.com/AdmiralGT/botc-scripts/assets/8020330/9a14b24e-7e11-4151-960f-f927d31e4db4)
how the script *should* look like, generated with botc-homebrew-script.vercel.app

hi @rsarvar1a

**Comment by AdmiralGT** [comment]
Turns out there was a problem with characters with underscores which I've fixed in https://github.com/AdmiralGT/botc-scripts/pull/346

In terms of incomplete translations, they're from the community provided spreadsheet and uses code provided by RealVidy to upload that into the Database. Without that code I'm not going to be able to update translations but if that can be restored then translations can be updated and extended.

**Comment by h3oCharles** [comment]
closing as the 1st half of the issue is solved and that's enough for me. As for the translation, I'll come back to that later once I'm ready to share my work
