### ISSUE TITLE
Bug:Ferryman is unformatted on script character lists

### ISSUE THREAD

**Issue by AggressivelyMemeing** [AdmiralGT/botc-scripts#368]
**Describe the bug**
The "Ferryman" Fabled character is not formatted on character lists

**When did it happen**
It is just a visual bug as of 05/02/2024. Unknown when this started, likely on the release of the Ferryman character.

**To Reproduce**
1. Go to https://botcscripts.com/script/2520/1.4.0
2. Click on "Characters"
3. Scroll down to "ferryman" on the character list on the right side of the preview
4. See ferryman unformatted

**Screenshots**
![image](https://github.com/AdmiralGT/botc-scripts/assets/86191833/1af2403f-7f13-4ec0-9ce8-c6c8a6c7cf09)

**Browser details:**
Chrome, Opera

**Additional context**
None

**Comment by AdmiralGT** [comment]
Thanks, this is now fixed, I wasn't aware of its official release so it wasn't in my character database
