### ISSUE TITLE
Bug: Can't alter my own script

### ISSUE THREAD

**Issue by LoftheT** [AdmiralGT/botc-scripts#450]
**Describe the bug**
I changed the name of one of my scripts with an upload, and now it's not showing in "My Scripts"

**When did it happen**
Around 9:40 BST 27/09/2024

**To Reproduce**
Is this problem reproduceable, if so, please provide the steps required to reproduce the behavior:
I went to an existing script
I updated the name of the script and released it as an update.
The original script was still showing in My Scripts (I since deleted it to try and fix it)
If I click on the script I can still upload new versions, but it still does not add it to my scripts

**Screenshots**
![image](https://github.com/user-attachments/assets/94a86ce9-9fdc-41a2-a662-205f904755e2)
![image](https://github.com/user-attachments/assets/f985cd25-4553-48ad-9150-47dfa540922e)

[Ooh, matron.json](https://github.com/user-attachments/files/17161852/Ooh.matron.json)
[Ooh, matron.pdf](https://github.com/user-attachments/files/17161853/Ooh.matron.pdf)

**Comment by AdmiralGT** [comment]
Thanks for reporting this. A script is uniquely identified by its name and so when "uploading a new version" you changed the name, it in fact just created a new script.

When you go to the Upload page from the NavBar there is an option to upload anonymously. This isn't present on the "Upload a new version" page and so I presume what happened here is that that defaulted to being anonymous and so the new script was uploaded without an owner.

I think https://github.com/AdmiralGT/botc-scripts/issues/307 is a suitable fix to this to prevent name changes when uploading a new version.

I've assigned https://botcscripts.com/script/4590/1.1.3 to your account @LoftheT , this should now appear under "My Scripts"
