### ISSUE TITLE
Bug:Custom script error 500

### ISSUE THREAD

**Issue by jjellinek** [AdmiralGT/botc-scripts#466]
**Describe the bug**
I'm trying to upload a custom/homebrew script. I receive an Error 500.

**When did it happen**
I am assuming from the announcement/notification that I should now be able to upload a script with custom characters/images. Apologies if I have misunderstood. I am logged in and attempting to Upload a script called "Rob's Birthday Herrrings"

**To Reproduce**
The json for this script is attached.
[Rob's Birthday Herrings.json](https://github.com/user-attachments/files/17619180/Rob.s.Birthday.Herrings.json)

Attempting to upload this gives me an Error 500.

**Comment by GrayPockets** [comment]
Happens to me to. Example: [Delerium Promenade](https://www.impeccabletiming.net/botc/Delirium%20Promenade.json)

**Comment by AdmiralGT** [comment]
Thanks for the reports all. I've made some database migrations and tested all the provided scripts. These all now uploaded successfully but I suspect some issues still to arise from the lack of schema validation. Please continue to report issues you find.

**Comment by GrayPockets** [comment]
This works now. It also allows me to make Minor versions! (it didn't used to let me do minor version updates)

**Comment by jjellinek** [comment]
Works for me too now, thanks :)

**Comment by DeeSang** [comment]
Iam having the same issue. (Iam not familiar with coding and these issues). would be great if i can get some help. Thank you

[Bloodline.json](https://github.com/user-attachments/files/20889648/Bloodline.json)
