### ISSUE TITLE
Bug: When I click "Link Account", I get an error message

### ISSUE THREAD

**Issue by GrayPockets** [AdmiralGT/botc-scripts#469]
**Describe the bug**
The "Link Account" button doesn't seem to work atm.

**When did it happen**
Today, multiple times.

**To Reproduce**
Is this problem reproduceable, if so, please provide the steps required to reproduce the behavior:
1. Go to https://botc-scripts.azurewebsites.net/
2. Login
3. Click Account -> Link Account

**Screenshots**
![image](https://github.com/user-attachments/assets/5d1053b9-8e2c-4858-8b85-6019154c6411)

**Comment by AdmiralGT** [comment]
Thanks for reporting, looks like this has broken recently with a package update. I'll try to resolve in the next 24 hours.

**Comment by AdmiralGT** [comment]
Ugh, I thought I had fixed this but it just looks like I didn't. Until I've deployed the fix you can access the link account page directly at https://botc-scripts.azurewebsites.net/account/social

**Comment by AdmiralGT** [comment]
A fix for this should now be deployed.

**Comment by GrayPockets** [comment]
Confirmed this is working again!
