### ISSUE TITLE
Bug: Bootlegger Fabled should not cause a script to count as Hybrid

### ISSUE THREAD

**Issue by GrayPockets** [AdmiralGT/botc-scripts#473]
**Describe the bug**
If you upload a fully homebrew script but it has the Bootlegger listed, it's marked as "Hybrid"

**When did it happen**
5:08 AM PST on 11/5/2024

**To Reproduce**
Is this problem reproduceable, if so, please provide the steps required to reproduce the behavior:
1. Go to https://botc-scripts.azurewebsites.net/script/5139
2. See that it's marked as Hybrid.

**Screenshots**
![image](https://github.com/user-attachments/assets/98ea4cfd-e404-4063-ba2f-079c5bc7b2de)

**Additional context**
[Fall of Rome.json](https://github.com/user-attachments/files/17632966/Fall.of.Rome.json)

**Comment by AdmiralGT** [comment]
Thanks for reporting this. I've deployed a fix and tested it with the Fall of Rome script provided and that's correctly marked as Homebrew. I've edited the Fall of Rome uploaded to change it's status to Homebrew but future uploads should now correctly ignore the Bootlegger token.

**Comment by GrayPockets** [comment]
Thank you so much!
