### ISSUE TITLE
Feature: change 'liked' scripts to show a like, not a thumbs down!

### ISSUE THREAD

**Issue by tobydjones** [AdmiralGT/botc-scripts#487]
**Description**
If I "favourite" a script, the outline of a star turns into a black star. So I can see which scripts I've favourited.
However, if I _haven't_ "liked" a script, it's shown with a green 'thumbs up', which looks like I _do_ like it
And if I do "like" a script that green 'thumbs up' turns into a **red** 'thumbs down', which looks like I _hate_ it!

A much better way would be to have an outline of a thumb that turns black just like the star does.
(white would look better, but that would be confusing because currently a white thumb means 'I have not liked this script')

Here's a mockup of the current situation, and my new version:

![image](https://github.com/user-attachments/assets/5853fdda-312e-40ef-aa00-80f2e9e1b277)

**Comment by AdmiralGT** [comment]
Thanks for the feedback. The button is reporting the action you can take, to either _like_ the script with the green thumbs up or to _unlike_ the script if you already like it with the red thumbs down. That also aligns to how the voting buttons used to be where blue voted and red unvoted but it had the word vote on and then it was changed to symbols. I agree that this may be a tad confusing with the favourite button somewhat having the opposite UI.

However, Likes are likely to disappear soon, see https://github.com/AdmiralGT/botc-scripts/issues/484 so I'm not going to change from the current behaviour.
